apiVersion: v1
kind: Service
metadata:
  name: doers-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 	arn:aws:acm:us-east-1:313263857607:certificate/5f7f4531-e716-4788-b816-20827de186fb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: doers-service
  ports:
    -  protocol: TCP
       port: 443
       targetPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: doers-service
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: doers-service
  targetCPUUtilizationPercentage: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doers-service
  labels:
    app: doers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doers-service
  template:
    metadata:
      labels:
        app: doers-service
    spec:
      containers:
        - image: dboss/doers:8
          name: doers-service
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=65"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "600Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 7
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: doers-service-config
